kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-all-namespaces-binding
subjects:
  - kind: ServiceAccount
    name: goprog
    namespace: afdev
roleRef:
  kind: ClusterRole
  name: view-all-namespaces
  apiGroup: rbac.authorization.k8s.io
