kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-resources-binding
  namespace: afdev
subjects:
  - kind: ServiceAccount
    name: goprog
    namespace: afdev
roleRef:
  kind: Role
  name: view-resources
  apiGroup: rbac.authorization.k8s.io


---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-resources-binding
  namespace: test-afdev
subjects:
  - kind: ServiceAccount
    name: goprog
    namespace: afdev
roleRef:
  kind: Role
  name: view-resources
  apiGroup: rbac.authorization.k8s.io
