kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: afdev
  name: view-resources
rules:
  - apiGroups: ["", "apps"]
    resources: ["services", "deployments", "pods"]
    verbs: ["get", "list", "watch"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-afdev
  name: view-resources
rules:
  - apiGroups: ["", "apps"]
    resources: ["services", "deployments", "pods"]
    verbs: ["get", "list", "watch"]
